version: '3'
services:
  app:
    image: python:3.10
    command: bash -c "pip install -r /opt/app/requirements.txt && python /opt/app/app.py"
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
